<?php
define("LATENIGHT_SONARR_API_ROOT", "");
define("LATENIGHT_SONARR_IMAGE_ROOT", "");
define("LATENIGHT_RADARR_API_ROOT", "");
define("LATENIGHT_RADARR_IMAGE_ROOT", "");
define("LATENIGHT_HOST_URL", "");
define("LATENIGHT_SONARR_APIKEY", "");
define("LATENIGHT_RADARR_APIKEY", "");
?>